##### Spring Application Information #####
spring.application.name=@artifactId@
server.servlet.context-path=/sb-docker-stack

##### Datasource Configuration #####
# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/sb_docker_stack_db?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

##### Hibernate (JPA) Configuration #####
# Show SQL statements in logs (Spring Boot-level property)
# By default, parameters are shown as '?' unless TRACE logging is enabled
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# If below is true: the output will be like: select * from user where id=? (for prod environment)
spring.jpa.properties.hibernate.show_sql=true
# Hibernate-level property
# Format SQL for readability (false: keep it in one line, true: each statement on separate lines)
spring.jpa.properties.hibernate.format_sql=false
# Highlight SQL keywords in the logs (can be removed if you want minimal output)
spring.jpa.properties.hibernate.highlight_sql=true
# Add SQL comments (can be removed if you want minimal output)
spring.jpa.properties.hibernate.use_sql_comments=false
# If DB schema is created by Hibernate, below should be true to ensure import.sql runs after the schema is created
spring.jpa.defer-datasource-initialization=true